# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kobrient
email: kobrient@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright © 2016 Kyle O'Brien
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kobrient.com" # the base hostname & protocol for your site
real_name:        "Kyle O'Brien"
twitter_username: kobrient
github_username:  kobrient
steam_username:   kobrient
reddit_username:  kobrient

# Build settings
markdown: kramdown
